LineLength:
  Max: 99

Documentation:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/BlockLength:
  Exclude:
  - "spec/**/*_spec.rb"

Style/PercentLiteralDelimiters:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Rails:
  Enabled: true

Rails/InverseOf:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
  - db/**/*
