# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: <%= 'a' * 30 %>

test:
  secret_key_base: <%= 'a' * 30 %>